export enum Role {
  ADMIN = "ADMIN",
  SITE_MANAGER = "SITE_MANAGER",
  TECHNICIAN = "TECHNICIAN",
  AUDITOR = "AUDITOR",
}

export enum DepreciationMethod {
  STRAIGHT_LINE = "STRAIGHT_LINE",
  DECLINING_BALANCE = "DECLINING_BALANCE",
  UNITS_OF_PRODUCTION = "UNITS_OF_PRODUCTION",
}

export enum UnitOfMeasure {
  CALENDAR = "CALENDAR",
  HOURS = "HOURS",
  TONNAGE = "TONNAGE",
}

export enum AssetStatus {
  ACTIVE = "ACTIVE",
  IN_MAINTENANCE = "IN_MAINTENANCE",
  DECOMMISSIONED = "DECOMMISSIONED",
  DISPOSED = "DISPOSED",
}

export enum ValuationEventType {
  DEPRECIATION = "DEPRECIATION",
  APPRECIATION = "APPRECIATION",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  MARKET_FEED = "MARKET_FEED",
}

export enum ValuationSource {
  SYSTEM_CALCULATED = "SYSTEM_CALCULATED",
  MANUAL_ENTRY = "MANUAL_ENTRY",
  MARKET_FEED = "MARKET_FEED",
}
